### ISSUE TITLE
Remove `nyholm/psr7` dependency

### ISSUE THREAD

**Issue by BrianHenryIE** [simPod/PhpJsonRpc#70]
It would be great to abstract away the `nyholm/psr7` dependency, in favour of `Psr\Http\Message\StreamFactoryInterface`.

I'm using this package in a project ([bh-php-monero-rpc](https://github.com/BrianHenryIE/bh-php-monero-rpc)), maybe when I have that finished I'll come back and address this issue!

Thank you for the work you've put into this.

**Comment by simPod** [comment]
Definitely! Care to send PR?
